import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // backend: [
  //   "intro",
  //   {
  //     type: "category",
  //     label: "API",
  //     items: ["api/rest", "api/graphql"],
  //   },
  // ],
};

export default sidebars;
