import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // frontend: [
  //   "intro",
  //   {
  //     type: "category",
  //     label: "Components",
  //     items: ["components/button", "components/input"],
  //   },
  // ],
};

export default sidebars;
